### ISSUE TITLE
What is the difference between this package and "react-date-picker" with "range" prop?

### ISSUE THREAD

**Issue by trevordmiller** [wojtekmaj/react-daterange-picker#25]
Per https://www.npmjs.com/package/react-date-picker

**Comment by wojtekmaj** [comment]
Hi there, good question!

React-Date-Picker by default returns a date being a beginning of a period a tile represents. For example, February 1st represents a time period from 2019-02-01T00:00:00.00 to 2019-02-01T23:59:59.999. The first of these dates is returned by default.

BUT because you have the ability to limit the number of views using `maxDetail` prop, effectively turning React-Date-Picker into a Month/Year/Decade or even a Century picker (I'm not judging you :D), date 2019-02-01T00:00:00.00 returned by default is unambiguous. Is it a beginning of a day picked, or a month picked?

Since your onChange handler may not know about which `maxDetail` are you using at the moment, `returnValue` was created so that you could figure out the exact period being selected.
