### ISSUE TITLE
 CSS.supports is not a function in test

### ISSUE THREAD

**Issue by haithemT** [wojtekmaj/react-daterange-picker#37]
using react-testing library and jest throw an error  `TypeError: CSS.supports is not a function`

temporary fix: adding `global.CSS = { supports: jest.fn() };`

the issue is related to react-fit package.

**update:** react-fit is used also in react-date-picker so i guess the same error should happen.

**Comment by wojtekmaj** [comment]
See wojtekmaj/react-fit#2 - this has been fixed in the latest react-fit release.

Since React-*-Picker all have "soft" dependency requirements (usually `^x.x.x`), you should be able to update React-Fit on your own by using `npm update react-fit` or `yarn upgrade react-fit`. Naturally, next versions of React-*-Picker will require newer React-Fit.

Let me know if this helps!
