### ISSUE TITLE
typescript support¿

### ISSUE THREAD

**Issue by IngenieroLata** [wojtekmaj/react-daterange-picker#38]
I'm looking for a library that handles date range selection for days, month and years but I'm currently using typescript. Any plan to include types definition here? I tried to generate one using `dts-gen` but couldn’t

**Comment by wojtekmaj** [comment]
I lean towards distributing typings in DefinitelyTyped, if anything, but I'm open to any contributions regarding TypeScript. 

This project is based on https://github.com/wojtekmaj/react-date-picker which has typings already, so they would be very similar. The only problem is that they are a little out of date and I can't fix them, because I'm unable to get TypeScript running correctly on a sample project, which stops me from testing them. See details in: https://github.com/wojtekmaj/react-date-picker/issues/168

**Comment by paambaati** [comment]
@wojtekmaj The linked issue (https://github.com/wojtekmaj/react-date-picker/issues/168) seems to have all linked PRs merged. Is there something else you require to close this issue?

**Comment by wojtekmaj** [comment]
Thanks for the heads up!
